apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: flask-app
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: flask-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: flask-app
    spec:
      containers:
      - image: mjbright/flask-web:v1
        imagePullPolicy: Always
        name: flask-app
        ports:
        - containerPort: 5000
        resources: {}
status: {}
